version: '3'
services:
  tf:
    build:
      context: .
      dockerfile: dockerfile
    image: contino/terraform
    volumes:
      - type: bind
        source: .
        target: /opt/app
    working_dir: /opt/app
    environment:
      - name=value
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    env_file: .env
