version: '3'
services:
  tf:
    build:
      context: .
      dockerfile: dockerfile
    image: contino/terraform
    volumes:
      - type: bind
        source: .
        target: /opt/app
    working_dir: /opt/app
    env_file: .env

