name: Build and Push to ECR
on:
  workflow_dispatch:
    branches:
      - master
  push:
    branches:
      - master
    paths:
      - 'weather-app.dockerfile'
      - '/src/**'
      - 'package*.json'
      - '/public/**'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      env:
        AWS_ACCESS_KEY_ID:      ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN:      ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_ACCOUNT_ID:         ${{ secrets.AWS_ACCOUNT_ID }}
        ECR_PW:                 ${{ secrets.ECR_PW }} 
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2  

    - name: docker login 

      run: make login

    - name: build image
      run: make build

    - name: push image
      run: make push

